language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
  
before_install:
  - sudo pip install websocket-client
# command to run tests
script: "sudo python slackit.py start"
